export const STUDENT = [
  {
    left: {
      id: "firstName",
      name: "firstName",
      label: "First Name",
      className: "profile_input",
      type: "text",
      disabled: false,
      show: true,
    },
    right: {
      id: "lastName",
      name: "lastName",
      label: "Last Name",
      className: "profile_input",
      type: "text",
      disabled: false,
      show: true,
    },
  },
  {
    left: {
      id: "email",
      name: "email",
      label: "Email",
      className: "profile_input",
      type: "email",
      disabled: false,
      show: true,
    },
    right: {
      id: "contactNo",
      name: "contactNo",
      label: "Contact No",
      className: "profile_input",
      type: "number",
      disabled: false,
      show: true,
    },
  },
  {
    left: {
      id: "courseOfStudy",
      name: "courseOfStudy",
      label: "Course Of Study",
      className: "profile_input",
      type: "text",
      disabled: false,
      show: true,
    },

    right: {
      id: "academicYear",
      name: "academicYear",
      label: "Academic Year",
      className: "profile_input",
      type: "text",
      disabled: false,
      show: true,
    },
  },
  {
    left: {
      id: "faculty",
      name: "faculty",
      label: "Faculty",
      className: "profile_input",
      type: "text",
      disabled: false,
      show: true,
    },
    right: {
      id: "department",
      name: "department",
      label: "Department",
      className: "profile_input",
      type: "text",
      disabled: false,
      show: true,
    },
  },
];
